package com.hireconnect.service;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.hireconnect.dto.request.PayrollRequest;
import com.hireconnect.dto.response.PayrollResponse;
import com.hireconnect.entity.PayrollHistory;
import com.hireconnect.entity.User;
import com.hireconnect.repository.PayrollHistoryRepository;
import com.hireconnect.repository.UserRepository;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Service
public class PayrollService {
    
    @Autowired
    private PayrollHistoryRepository payrollHistoryRepository;
    
    @Autowired
    private UserRepository userRepository;
    
    
    private PayrollResponse enrichPayrollWithUserDetails(PayrollHistory payroll) {
    	PayrollResponse dto = new PayrollResponse();
        
        
        dto.setId(payroll.getId());
        dto.setUserId(payroll.getUserId());
        dto.setUserName(payroll.getUserName());
        dto.setPayrollMonth(payroll.getPayrollMonth());
        dto.setBasicSalary(payroll.getBasicSalary());
        dto.setHra(payroll.getHra());
        dto.setConveyanceAllowance(payroll.getConveyanceAllowance());
        dto.setMedicalAllowance(payroll.getMedicalAllowance());
        dto.setLta(payroll.getLta());
        dto.setOtherAllowances(payroll.getOtherAllowances());
        dto.setTotalEarnings(payroll.getTotalEarnings());
        dto.setPfEmployee(payroll.getPfEmployee());
        dto.setProfessionalTax(payroll.getProfessionalTax());
        dto.setTaxDeductions(payroll.getTaxDeductions());
        dto.setOtherDeductions(payroll.getOtherDeductions());
        dto.setTotalDeductions(payroll.getTotalDeductions());
        dto.setNetSalary(payroll.getNetSalary());
        dto.setLopDays(payroll.getLopDays());
        dto.setOvertimeHours(payroll.getOvertimeHours());
        dto.setStatus(payroll.getStatus());
        dto.setPaymentDate(payroll.getPaymentDate());
        dto.setPayslipGenerated(payroll.getPayslipGenerated());
        dto.setPayslipPath(payroll.getPayslipPath());
        dto.setAutoGenerated(payroll.getAutoGenerated());
        dto.setRemarks(payroll.getRemarks());
        dto.setCreatedAt(payroll.getCreatedAt());
        
        
        try {
            User user = userRepository.findById(payroll.getUserId()).orElse(null);
            if (user != null) {
                dto.setEmployeeId(user.getEmployeeId() != null ? user.getEmployeeId() : "EMP-" + user.getId());
                dto.setEmployeeName(user.getFullName());
                dto.setJoiningDate(user.getCreatedAt()); 
                
                
                dto.setSource(payroll.getAutoGenerated() ? "Auto Generated" : "Manual Entry");
                
                if (payroll.getPayrollMonth() != null) {
                    dto.setPayPeriod(payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("MMMM yyyy")));
                    dto.setPayDate(payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("dd MMM yyyy")));
                }
            } else {
               
                dto.setEmployeeId("N/A");
                dto.setEmployeeName(payroll.getUserName() != null ? payroll.getUserName() : "Unknown");
                dto.setJoiningDate(null);
            }
        } catch (Exception e) {
            
            dto.setEmployeeId("N/A");
            dto.setEmployeeName(payroll.getUserName() != null ? payroll.getUserName() : "Unknown");
            dto.setJoiningDate(null);
        }
        
        return dto;
    }
    
    
    public List<PayrollResponse> getAllPayrolls() {
        List<PayrollHistory> payrolls = payrollHistoryRepository.findAll();
        return payrolls.stream()
            .map(this::enrichPayrollWithUserDetails)
            .collect(Collectors.toList());
    }
    
    
    public PayrollResponse getPayrollById(Long id) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        return enrichPayrollWithUserDetails(payroll);
    }
    
    
    public List<PayrollResponse> getPayrollByUser(Long userId) {
        List<PayrollHistory> payrolls = payrollHistoryRepository.findByUserIdOrderByPayrollMonthDesc(userId);
        return payrolls.stream()
            .map(this::enrichPayrollWithUserDetails)
            .collect(Collectors.toList());
    }
    
    @Transactional
    public PayrollHistory createPayroll(PayrollRequest request) {
        if (request.getPayrollMonth() != null && request.getUserId() != null) {
            payrollHistoryRepository.findByUserIdAndMonth(request.getUserId(), request.getPayrollMonth())
                .ifPresent(existing -> {
                    throw new RuntimeException("Payroll already exists for this month");
                });
        }
        
        PayrollHistory payroll = new PayrollHistory();
        mapRequestToEntity(request, payroll);
        
        return payrollHistoryRepository.save(payroll);
    }
    
    @Transactional
    public PayrollHistory updatePayroll(Long id, PayrollRequest request) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        mapRequestToEntity(request, payroll);
        
        return payrollHistoryRepository.save(payroll);
    }
    
    @Transactional
    public void deletePayroll(Long id) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        payrollHistoryRepository.delete(payroll);
    }
    
    @Transactional
    public PayrollHistory generateAutoPayroll(PayrollRequest request) {
        return createPayroll(request);
    }
    
    @Transactional
    public PayrollHistory manualPayrollEntry(PayrollRequest request) {
        return createPayroll(request);
    }
    
    public Map<String, Object> getAnalytics(String range) {
        Map<String, Object> analytics = new HashMap<>();
        
        long totalEmployees = userRepository.countByRole(User.Role.EMPLOYEE);
        analytics.put("totalEmployees", totalEmployees);
        
        LocalDate now = LocalDate.now();
        LocalDate currentMonth = LocalDate.of(now.getYear(), now.getMonth(), 1);
        List<PayrollHistory> currentMonthPayrolls = payrollHistoryRepository.findByYearAndMonth(
            currentMonth.getYear(), currentMonth.getMonthValue()
        );
        analytics.put("activePayrolls", currentMonthPayrolls.size());
        
        BigDecimal totalPayouts = currentMonthPayrolls.stream()
            .map(PayrollHistory::getTotalEarnings)
            .reduce(BigDecimal.ZERO, BigDecimal::add);
        analytics.put("totalPayouts", totalPayouts);
        
        analytics.put("pendingReimbursements", 0);
        
        return analytics;
    }
    
    public ResponseEntity<?> exportPayrolls(String format, String status, String month) {
        List<PayrollHistory> payrolls;
        
        if (!"all".equals(status)) {
            payrolls = payrollHistoryRepository.findByStatus(
                PayrollHistory.PayrollStatus.valueOf(status.toUpperCase())
            );
        } else {
            payrolls = payrollHistoryRepository.findAll();
        }
        
        return ResponseEntity.ok(Map.of("message", "Export functionality to be implemented"));
    }
    
    @Transactional
    public Map<String, Object> generatePayslip(Long payrollId) throws IOException, DocumentException {
        PayrollHistory payroll = payrollHistoryRepository.findById(payrollId)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + payrollId));
        User user = userRepository.findById(payroll.getUserId())
            .orElseThrow(() -> new RuntimeException("User not found"));
        
        File uploadsDir = new File("uploads/payslips");
        if (!uploadsDir.exists()) {
            uploadsDir.mkdirs();
        }
        
        String fileName = "payslip_" + payroll.getUserId() + "_" + 
                         payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("yyyy_MM")) + ".pdf";
        String filePath = "uploads/payslips/" + fileName;
        
        generatePayslipPDF(payroll, user, filePath);
        
        payroll.setPayslipGenerated(true);
        payroll.setPayslipPath("/uploads/payslips/" + fileName);
        payrollHistoryRepository.save(payroll);
        
        Map<String, Object> result = new HashMap<>();
        result.put("message", "Payslip generated successfully");
        result.put("filePath", "/uploads/payslips/" + fileName);
        
        return result;
    }
    
    public ResponseEntity<Resource> downloadPayslip(Long payrollId) {
        PayrollHistory payroll = payrollHistoryRepository.findById(payrollId)
            .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + payrollId));
        
        if (!payroll.getPayslipGenerated() || payroll.getPayslipPath() == null) {
            throw new RuntimeException("Payslip not generated yet");
        }
        
        File file = new File("." + payroll.getPayslipPath());
        if (!file.exists()) {
            throw new RuntimeException("Payslip file not found");
        }
        
        Resource resource = new FileSystemResource(file);
        
        return ResponseEntity.ok()
            .contentType(MediaType.APPLICATION_PDF)
            .header(HttpHeaders.CONTENT_DISPOSITION, 
                   "attachment; filename=\"" + file.getName() + "\"")
            .body(resource);
    }
    
    private void mapRequestToEntity(PayrollRequest request, PayrollHistory payroll) {
        payroll.setUserId(request.getUserId());
        payroll.setUserName(request.getUserName()); 
        payroll.setPayrollMonth(request.getPayrollMonth());
        payroll.setBasicSalary(request.getBasicSalary());
        payroll.setHra(request.getHra());
        payroll.setConveyanceAllowance(request.getConveyanceAllowance());
        payroll.setMedicalAllowance(request.getMedicalAllowance());
        payroll.setLta(request.getLta());
        payroll.setOtherAllowances(request.getOtherAllowances());
        payroll.setPfEmployee(request.getPfEmployee());
        payroll.setProfessionalTax(request.getProfessionalTax());
        payroll.setTaxDeductions(request.getTaxDeductions());
        payroll.setOtherDeductions(request.getOtherDeductions());
        payroll.setLopDays(request.getLopDays());
        payroll.setOvertimeHours(request.getOvertimeHours());
        payroll.setAutoGenerated(request.getAutoGenerated());
        payroll.setTotalEarnings(request.getTotalEarnings());
        payroll.setTotalDeductions(request.getTotalDeductions());
        payroll.setNetSalary(request.getNetSalary());
    }
    
    private void generatePayslipPDF(PayrollHistory payroll, User user, String filePath) 
            throws IOException, DocumentException {
        
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();
        
        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
        Paragraph title = new Paragraph("PAYSLIP", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        
        document.add(new Paragraph("\n"));
        
        // 🔥 UPDATED: Use employeeId instead of user ID
        String employeeId = user.getEmployeeId() != null ? user.getEmployeeId() : "EMP-" + user.getId();
        document.add(new Paragraph("Employee Name: " + user.getFullName()));
        document.add(new Paragraph("Employee ID: " + employeeId));
        document.add(new Paragraph("Joining Date: " + (user.getCreatedAt() != null ? 
            user.getCreatedAt().format(DateTimeFormatter.ofPattern("dd MMM yyyy")) : "N/A")));
        document.add(new Paragraph("Month: " + payroll.getPayrollMonth().format(
            DateTimeFormatter.ofPattern("MMMM yyyy"))));
        
        document.add(new Paragraph("\n"));
        
        Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
        
        PdfPTable earningsTable = new PdfPTable(2);
        earningsTable.setWidthPercentage(100);
        
        addTableHeader(earningsTable, "EARNINGS", boldFont);
        addTableRow(earningsTable, "Basic Salary", payroll.getBasicSalary());
        addTableRow(earningsTable, "HRA", payroll.getHra());
        addTableRow(earningsTable, "Conveyance", payroll.getConveyanceAllowance());
        addTableRow(earningsTable, "Medical", payroll.getMedicalAllowance());
        addTableRow(earningsTable, "LTA", payroll.getLta());
        addTableRow(earningsTable, "Other Allowances", payroll.getOtherAllowances());
        addTableRow(earningsTable, "Total Earnings", payroll.getTotalEarnings(), boldFont);
        
        document.add(earningsTable);
        document.add(new Paragraph("\n"));
        
        PdfPTable deductionsTable = new PdfPTable(2);
        deductionsTable.setWidthPercentage(100);
        
        addTableHeader(deductionsTable, "DEDUCTIONS", boldFont);
        addTableRow(deductionsTable, "PF", payroll.getPfEmployee());
        addTableRow(deductionsTable, "Professional Tax", payroll.getProfessionalTax());
        addTableRow(deductionsTable, "Income Tax", payroll.getTaxDeductions());
        addTableRow(deductionsTable, "Other Deductions", payroll.getOtherDeductions());
        addTableRow(deductionsTable, "Total Deductions", payroll.getTotalDeductions(), boldFont);
        
        document.add(deductionsTable);
        document.add(new Paragraph("\n"));
        
        Font netSalaryFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
        Paragraph netSalary = new Paragraph(
            "Net Salary: ₹" + payroll.getNetSalary(), netSalaryFont);
        netSalary.setAlignment(Element.ALIGN_RIGHT);
        document.add(netSalary);
        
        document.close();
    }
    
    private void addTableHeader(PdfPTable table, String header, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(header, font));
        cell.setColspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }
    
    private void addTableRow(PdfPTable table, String label, BigDecimal value) {
        table.addCell(label);
        table.addCell("₹" + (value != null ? value.toString() : "0"));
    }
    
    private void addTableRow(PdfPTable table, String label, BigDecimal value, Font font) {
        PdfPCell labelCell = new PdfPCell(new Paragraph(label, font));
        PdfPCell valueCell = new PdfPCell(new Paragraph("₹" + (value != null ? value.toString() : "0"), font));
        table.addCell(labelCell);
        table.addCell(valueCell);
    }
}